### PR TITLE
Add unit tests for com.oath.halodb.histo.EstimatedHistogram

### PR DESCRIPTION
**Pull request by Braavos96**
I've analysed your codebase and noticed that `com.oath.halodb.histo.EstimatedHistogram` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.

### CODE REVIEW

**Comment by wangtao724** [comment]
@Braavos96 Appreciated for your contribution to the project. We will review the tests and have it merged if everything is good.

**Comment by Braavos96** [comment]
Hi @wangtao724 just following up and wondering if you would like me to make any changes to the PR?

**Comment by wangtao724** [comment]
@Braavos96 Are these tests added manually or generated automatically by the Diffblue Cover tool? Why upgrade "maven-surefire-plugin", is it required for your tests? Moreover, please make the PR build pass

**Comment by Braavos96** [comment]
Hi @wangtao724 these units tests have been automatically written by Diffblue Cover but we do spend a small amount of time refactoring them to fit the project testing style e.g test names. Done the `maven-surefire-plugin` was my mistake and the PR is now building on Travis

**Comment by Braavos96** [comment]
Hi @wangtao724 just following up and wondering if you would like me to make any more changes to the PR?

**Pull request merged**
